name: SCA Resolver Example

on:
  push:
    branches:
      [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Go 1.17.6
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.6
 
#      - name: setup go 1.7.6
#        run: |
#          wget https://go.dev/dl/go1.17.6.linux-amd64.tar.gz
#          tar -C /home/runner -xzf go1.17.6.linux-amd64.tar.gz
#          export GOROOT="/home/runner/go"
#          export GOBIN="$HOME/go/bin"
#          mkdir -p $GOBIN
#          export PATH=$PATH:$GOROOT/bin:$GOBIN
#        shell: bash
        
      - name: Download dependencies
        run: go get -u -v ./... 
      
      - name: Build project
        run: go build -o ./bin/cx ./cmd
      
      - name: Test go mod is installed by running go mo verify
        run: go mod verify
      
      - name: Download SCA Resolver
        run: |
          wget https://sca-downloads.s3.amazonaws.com/cli/latest/ScaResolver-linux64.tar.gz
          tar -xzvf ScaResolver-linux64.tar.gz
          rm -rf ScaResolver-linux64.tar.gz
      
      - name: Checkmarx AST CLI Action
        uses: checkmarxDev/ast-github-action@master
        with:
          project_name: ast-cli
          base_uri: ${{ secrets.CX_BASE_URI }}
          cx_tenant: ${{ secrets.CX_TENANT }}
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
          additional_params: --scan-types sast,kics,sca --report-format sarif --output-name results 
#         additional_params: --sca-resolver ./ScaResolver --file-filter !readme --report-format sarif --output-name results --scan-types sast,kics,sca
#          additional_params: --sca-resolver ./ScaResolver --debug --report-format sarif --output-name results 
       
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: results.sarif
